#@apiUrl = http://localhost:3030/notes
@apiUrl = https://notes-emme.azurewebsites.net/notes
@token = {{$dotenv TOKEN}}

###
GET {{apiUrl}}
Authorization: Bearer {{token}}

###

GET {{apiUrl}}/64ff00e6e1e01909c92b8174
Authorization: Bearer {{token}}

###
POST {{apiUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
"text": "Note2"
}

###
PATCH {{apiUrl}}/64feeaf737322583eaa8526b
Content-Type:  application/json

{
    "text": "My updated note"
}

###
DELETE {{apiUrl}}/64feeaf737322583eaa8526b

###