@apiUrl = http://localhost:3030/notes/

###
GET {{apiUrl}}

###

GET {{apiUrl}}/64f9a91081d13b8791f52582


###
POST {{apiUrl}}
Content-Type: application/json

{
"text": "Note2"
}

###
PATCH {{apiUrl}}/64f9b40c9035b26bc4682229
Content-Type:  application/json

{
    "text": "My updated note"
}

###
DELETE {{apiUrl}}/64f9b40c9035b26bc4682229

###